site_name: Gradual Machine Learning(GML) framework
theme: readthedocs
nav:
  - introduction: goal.md
  - Installation and Usage: usage.md
  - example: example.md
  - data_structures: data_structures.md
  - parameter_description: parameter_description.md
  - API: gml.md 
collapse_single_pages: true